<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>926750c0-5ce8-4711-bda3-ecb464b0628d</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
        <PackageReference Include="CloudinaryDotNet" Version="1.29.3" />
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="MailKit" Version="4.18.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.12">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.17.8" />
        <PackageReference Include="StackExchange.Redis" Version="3.3.0" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.23.0" />
    </ItemGroup>

    <ItemGroup>
        <Content Update="Db/Seeds/**/*.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
        <None Update="Db/Seeds/**/*.gz;Db/Seeds/*.csv;Db/Seeds/*.md" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
        <Compile Remove="Tests/**/*.cs" />
        <Content Remove="Tests/**" />
        <None Remove="Tests/**" />
    </ItemGroup>

</Project>
