<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Db/Seeds/*.cs" Exclude="../../Db/Seeds/SeedImportDatabase.cs" Link="Seeds/%(Filename)%(Extension)" />
    <Compile Include="../../Db/models/*.cs" Link="Models/%(Filename)%(Extension)" />
    <Compile Include="../../Shared/enums/*.cs" Link="Enums/%(Filename)%(Extension)" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CloudinaryDotNet" Version="1.29.3" />
  </ItemGroup>
</Project>
